apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/olagunjuraman/jean-consulting.git'
    path: applications
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
