# app1.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: test
spec:
  project: default
  source:
    repoURL: ''
    chart: prometheus
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test
