# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: example2
#   namespace: test
# spec:
#   project: default
#   source:
#     repoURL: 'https://prometheus-community.github.io/helm-charts'
#     chart: prometheus
#     targetRevision: '15.5.3'
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: test



# demo-dev/applications/prometheus.yaml

# demo-dev/applications/grafana.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    repoURL: https://github.com/grafana/helm-charts
    targetRevision: main
    path: charts/grafana
    helm:
      valueFiles:
        - values/grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
